### ISSUE TITLE
SDL error

### ISSUE THREAD

**Issue by carson** [freider/keiro#1]
I was copy and pasting from the readme and hit an error about SDL:

```
clang: warning: argument unused during compilation: '-mno-fused-madd'

In file included from src/_numericsurfarray.c:23:

src/pygame.h:106:10: fatal error: 'SDL.h' file not found

#include <SDL.h>

     ^

1 error generated.
```

---

I figure the workaround is "brew install sdl" and then re-ran the pip command in a fresh terminal

**Comment by Enigman2011** [comment]
Guys i have a problem with this.when i run `python run.py` this comes:

`Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Traceback (most recent call last):
  File "run.py", line 180, in <module>
    run();
  File "run.py", line 176, in run
    simulation.run()
  File "run.py", line 82, in run
    if not verify_untouched_files(self.git):
  File "run.py", line 42, in verify_untouched_files
    unstaged = git.unstaged_changes()
  File "/home/nima/Desktop/keiro-master/keiro/git.py", line 38, in unstaged_changes
    return self.git_lines(["diff", "--name-only"])
  File "/home/nima/Desktop/keiro-master/keiro/git.py", line 33, in git_lines
    self.git_output(cmd).split('\n')
  File "/home/nima/Desktop/keiro-master/keiro/git.py", line 27, in git_output
    self.git_cmd(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'diff', '--name-only']' returned non-zero exit status 129`
can anyone help me out with this?

**Comment by alexanderGGreenberg** [comment]
@Enigman2011 I'm having the same issue with the exact same command, and you are the only one online who seems to have encountered it too, did you ever find a solution?
