### ISSUE TITLE
`python run.py` Error

### ISSUE THREAD

**Issue by Enigman2011** [freider/keiro#2]
Guys i have a problem with this.when i run python run.py this comes:

`Not a git repository To compare two paths outside a working tree: 
usage: git diff [--no-index] <path> <path> 
Traceback (most recent call last): File "run.py", line 180, in <module> 
run(); 
File "run.py", line 176, in run simulation.run() 
File "run.py", line 82, in run if not verify_untouched_files(self.git): 
File "run.py", line 42, in verify_untouched_files unstaged = git.unstaged_changes() 
File "/home/nima/Desktop/keiro-master/keiro/git.py", line 38, in unstaged_changes return self.git_lines(["diff", "--name-only"]) 
File "/home/nima/Desktop/keiro-master/keiro/git.py", line 33, in git_lines self.git_output(cmd).split('\n') 
File "/home/nima/Desktop/keiro-master/keiro/git.py", line 27, in git_output self.git_cmd(cmd) 
File "/usr/lib/python2.7/subprocess.py", line 573, in check_output raise CalledProcessError(retcode, cmd, output=output) subprocess.CalledProcessError: Command '['git', 'diff', '--name-only']' returned non-zero exit status 129`
can anyone help me out with this?

**Comment by freider** [comment]
Hi! When you run the run script it assumes you are running it from a cloned version of this git repo (or a fork) and it warns you if you have any un-committed code. If you aren't running from a git repository, or don't want the warning, you can run the script with the `--no-gitcheck` (or -G for short) flag which will disable this check. Let me know if that helps!
